name: Build app executable with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-upload:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install pyinstaller -U
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed GameInterfaceForToys.py

    - name: Include configuration data
      run: |
        Copy "data" "dist\data\"
        Copy "games" "dist\games\"

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist-files
        path: dist/*
